# -*- coding: utf-8 -*-
"""terminology-extraction-v02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/bogdanbabych/0945BUT10211/blob/main/terminology_extraction_v02.ipynb
"""



"""## Terminology extraction with Python
this is a script which will extract terminology from comparable corpora

"""

import os, re, sys

class clProcCorpus(object):
	'''
	reading corpus, extracting terms with PoS patterns
	'''

	def __init__(self, FileIN):
		self.DTerms = {}
		self.readCorpus(FileIN)


	def readCorpus(self, FileIN):
		LTerm = []
		for SLine in FileIN:
			LLine = re.split('\t', SLine)
			# sys.stderr.write(str(LLine) + '\n')

			try:
				SWord = LLine[0]
				SPoS = LLine[1]
				SLemma = LLine[2]
			except:
				SWord = ''
				SPoS = ''
				SLemma = ''

			# if re.match('J.*', SPoS) or re.match('N.*', SPoS) or re.match('of', SWord):
			if re.match('ADJ.*', SPoS) or re.match('N\..*', SPoS) or re.match('von', SWord):
				LTerm.append(SWord)
			else:
				STerm = ' '.join(LTerm)
				LTerm = []
				try:
					self.DTerms[STerm] += 1
				except:
					self.DTerms[STerm] = 1

		return

# FileN = open('./content/gnu2021en_l.vert.aa', 'r', encoding='utf8')
FileN = open('./content/gnu2021de_l.vert.aa', 'r', encoding='utf8')

OProcCorpus = clProcCorpus(FileN)

# FileO = open('./content/gnu2021en_l.terms', 'w')
FileO = open('./content/gnu2021de_l.terms', 'w')

for STerm, Frq in sorted(OProcCorpus.DTerms.items(), key=lambda x: x[1], reverse=True):
	FileO.write(STerm + '\t' + str(Frq) + '\n')